## EDUNET FOUNDATION - Self-Practice Exercise Notebook

### LAB 8 - Implementing Numpy Concepts in Python

Problem 1: Write a NumPy program to test whether none of the elements of a given array are zero.

In [2]:
import numpy as np
n=np.array([1,2,3,4,5])
m=np.array([0,1,2,3,4])
for i in n:
    if i==0:
        res="This Array Contains Zeros"
        break
    else:
        res="This Array don't Contains Zeros"
print(res)
for i in m:
    if i==0:
        res="This array Contains Zeros"
        break
    else:
        res="This array don't Contains Zeros"
print(res)

This Array don't Contains Zeros
This array Contains Zeros


Problem 2: Write a NumPy program to create an array of 10 zeros, 10 ones, and 10 fives. 

In [3]:
print(np.zeros(10))
print(np.ones(10))
n=np.array([])
for _ in range(11):
    n=np.append(n,5)
print(n)
    

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


Problem 3: Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution.

In [4]:
import numpy as np
r = np.random.randn(15)
print(r)

[ 0.25889011 -1.84304367 -0.42453601 -1.57249314  0.83866837  0.26592837
  0.37879086  0.17860457  1.88793565  1.07828669  0.64780387 -1.33545529
  0.75431657 -1.46624501 -0.40979214]


Problem 4: Write a NumPy program to create a two-dimensional array with shape (8,5) of random numbers. Select random numbers from a normal distribution (200,7).

In [6]:
import numpy as np
mean = 200
std_dev = 7
random_numbers = np.random.normal(mean, std_dev, (8, 5))
print(random_numbers)

[[190.79391499 207.34942648 207.24854575 201.03859084 214.70131065]
 [200.49209545 195.75395062 203.90712826 200.29039356 204.36277398]
 [189.8443115  198.8074204  210.24427997 206.88660963 196.62912595]
 [197.48625816 194.63453916 190.70450673 202.03426461 207.66369074]
 [193.68964651 187.01992949 184.6115333  213.58448099 194.15825674]
 [193.66804781 199.9441088  191.190336   200.7600042  192.98720487]
 [195.48204237 199.9634629  210.66362407 206.88450739 202.87780463]
 [218.5558935  197.89981312 204.16717572 197.33630311 201.14716079]]


Problem 5: Write a NumPy program to create a 4x4 array. Create an array from said array by swapping first and last, second and third columns.

In [8]:
import numpy as np
original_array = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])
swapped_array = original_array[:, [3, 1, 2, 0]]
print("Original Array:")
print(original_array)
print("\nSwapped Array:")
print(swapped_array)

Original Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Swapped Array:
[[ 4  2  3  1]
 [ 8  6  7  5]
 [12 10 11  9]
 [16 14 15 13]]


Problem 6: Write a NumPy program to swap rows and columns of a given array in reverse order.

In [9]:
import numpy as np
original_array = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])
reversed_rows = original_array[::-1]
reversed_columns = original_array[:, ::-1]
swapped_array = reversed_rows[:, ::-1]
print("Original Array:")
print(original_array)
print("\nSwapped Array:")
print(swapped_array)

Original Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Swapped Array:
[[16 15 14 13]
 [12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


Problem 7: Write a NumPy program to multiply two given arrays of the same size element-by-element.

In [11]:
import numpy as np
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
res = arr1 * arr2
print(res)

[[ 5 12]
 [21 32]]


Problem 8: Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.

In [12]:
import numpy as np
values = np.arange(2, 11)
mat = values.reshape(3, 3)
print(mat)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


Problem 9: Write a NumPy program to create a 3x3x3 array with random values.
Expected Output:

[[[ 0.48941799 0.58722213 0.43453926]
[ 0.94497547 0.81081709 0.1510409 ]
[ 0.66657127 0.29494755 0.48047144]]
[[ 0.02287253 0.95232614 0.32264936]
[ 0.67009741 0.25458304 0.16290913]
[ 0.15520198 0.86826529 0.9679322 ]]
[[ 0.13503103 0.02042211 0.24683897]
[ 0.97852158 0.22374748 0.10798856]
[ 0.62032646 0.5893892 0.16958144]]]

In [21]:
import numpy as np
r = np.random.rand(3, 3, 3)
print(r)

[[[0.41742547 0.02181609 0.83291539]
  [0.09774561 0.84377275 0.54654973]
  [0.28765095 0.53461106 0.93814954]]

 [[0.05038161 0.89867239 0.45420517]
  [0.34716367 0.65433008 0.58786461]
  [0.63928362 0.51211792 0.07588284]]

 [[0.41174461 0.27694256 0.36054077]
  [0.06480478 0.70963324 0.06484372]
  [0.13355717 0.47673193 0.34348882]]]


Problem 10: Write a Python program to find the maximum and minimum value of a given flattened array.

In [23]:
import numpy as np
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
flattened_array = array.flatten()
max_value = np.amax(flattened_array)
min_value = np.amin(flattened_array)
print("Maximum value:", max_value)
print("Minimum value:", min_value)


Maximum value: 9
Minimum value: 1


Problem 11: Write a NumPy program to add, subtract, multiply, divide arguments element-wise.     
Expected Output:
Add:
5.0
Subtract:
-3.0
Multiply:
4.0
Divide:
0.25

In [25]:
n1=np.array([1])
n2=np.array([4])
print("Add:",float(n1+n2))
print("Subtract:",float(n1-n2))
print("Multiply:",float(n1*n2))
print("Divide:",float(n1/n2))

Add: 5.0
Subtract: -3.0
Multiply: 4.0
Divide: 0.25


Problem 12: Write a NumPy program to get the powers of an array values element-wise.
Note: First array elements raised to powers from second array
Expected Output:
Original array
[0 1 2 3 4 5 6]
First array elements raised to powers from second array, element-wise:
[ 0 1 8 27 64 125 216]

In [27]:
n1=np.array([0,1,2,3,4,5,6])
n2=np.array([3])
print(n1**n2)

[  0   1   8  27  64 125 216]


Problem 13: Create a Python project to guess a number that has randomly selected.

In [33]:
n=np.random.randint(1,11)
s=int(input("Enter a random Number from 1 to 10:"))
if n==s:
      print("You Gussed the Correct Number")
else:
      print("you Guessed the wrong number. The random number is:"+str(n))

Enter a random Number from 1 to 10:8
you Guessed the wrong number. The random number is:7


Problem 14: Write a NumPy program to create a 2D array with 1 on the border and 0 inside.        
Expected Output:
Original array:
[[ 1. 1. 1. 1. 1.]
...................
[ 1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array
[[ 1. 1. 1. 1. 1.]
...................
[ 1. 1. 1. 1. 1.]]

In [35]:
import numpy as np
rows, cols = 5, 5
array = np.zeros((rows, cols))
array[0, :] = 1  
array[-1, :] = 1 
array[:, 0] = 1  
array[:, -1] = 1 
print("array:")
print(array.astype(int))

array:
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


Problem 15: Write a NumPy program to append values to the end of an array.                      
Expected Output:
Original array:
[10, 20, 30]
After append values to the end of the array:
[10 20 30 40 50 60 70 80 90]

In [36]:
arr=np.array([10,20,30])
arr2=np.array([40,50,60,70,80,90])
arr=np.append(arr,arr2)
print(arr)

[10 20 30 40 50 60 70 80 90]
